CREATE TABLE `SAMPLE_BOARD` (
    `BOARD_NO` bigint(20) NOT NULL AUTO_INCREMENT,
    `BOARD_NAME` varchar(50) NOT NULL,
    `OWNER_ID` varchar(50) NOT NULL,
    `CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
    `UPDATED_AT` datetime DEFAULT NULL,
    PRIMARY KEY (`BOARD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4;