CREATE TABLE `SAMPLE_BOARD` (
    `BOARD_NO` bigint(20) NOT NULL AUTO_INCREMENT,
    `BOARD_NAME` varchar(50) NOT NULL,
    `OWNER_ID` varchar(50) NOT NULL,
    `CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
    `UPDATED_AT` datetime DEFAULT NULL,
    PRIMARY KEY (`BOARD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4;


-- 사용자 관리
CREATE TABLE USER (
    USER_ID VARCHAR(20) NOT NULL COMMENT '사용자ID',
    USER_NM VARCHAR(20) NOT NULL COMMENT '사용자명',
    DEPT_ID VARCHAR(20) NULL COMMENT '부서아이디',
    DELETE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
    CREATED_AT DATETIME NOT NULL DEFAULT current_timestamp(),
    UPDATED_AT DATETIME DEFAULT NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4;

-- 부서 관리
CREATE TABLE DEPT (
    DEPT_ID VARCHAR(20) NOT NULL COMMENT '부서아이디',
    DEPT_NM VARCHAR(50) NOT NULL COMMENT '부서명',
    MANAGER_ID VARCHAR(20) NULL COMMENT '입력담당자ID',
    CREATED_AT DATETIME NOT NULL DEFAULT current_timestamp(),
    UPDATED_AT DATETIME DEFAULT NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (DEPT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4;