/* 관리자 취합문서 현황 조회 */
WITH COMBINED AS
(
    SELECT	A.*
    FROM   	COMBINED_DOC A
    WHERE	1 = 1
    ORDER BY A.COMDOC_SEQ DESC
    LIMIT 1 BY D.DOCTYPE_ID
)
SELECT
        B.DOCTYPE_ID
    ,	B.COMDOC_SEQ
    ,   (
            SELECT
					DOCTYPE_NAME
			FROM	DOC_TYPE DT
			WHERE	DT.DOCTYPE_ID = B.DOCTYPE_ID
		) AS DOCTYPE_NAME	/* 문서명 */
     ,	(
            SELECT	DEPT_NAME
            FROM	DEPARTMENT DEPT
            WHERE	DEPT.DEPT_ID = B.DEPT_ID
        ) AS DEPT_NAME /* 부서명 */
     ,	IF (D.DOCUMENTS_SEQ IS NOT NULL, 'Y', 'N') /* 부서별 입력 여부 */
FROM	COMBINED A
            LEFT JOIN DOCKTYPE_DUTY B ON A.DOCTYPE_ID = B.DOCTYPE_ID
            LEFT JOIN DOCUMENTS D ON A.COMDOC_SEQ = D.COM_DOC_SEQ
WHERE 1 = 1
;


/* 입력자별 입력문서 현황 조회 */
WITH COMBINED AS
(
    SELECT	*
    FROM   	COMBINED_DOC A
    WHERE	1 = 1
    ORDER BY A.COMDOC_SEQ DESC
    LIMIT 1 BY D.DOCTYPE_ID
)
SELECT	B.*
FROM	DOCTYPE_DUTY A
            LEFT JOIN COMBINED B ON A.DOCTYPE_ID = B.DOCTYPE_ID
WHERE	1 = 1
AND		A.USER_ID = #{userId:VARCHAR}
;